language: r
r:
  - release
  - devel
r_packages:
  - covr
cache: packages
sudo: false
warnings_are_errors: true
addons:
    apt:
        packages:
        - ghostscript
after_success:
  - Rscript -e 'library(covr); codecov()'
