language: r
r:
  - release
  - devel
r_packages:
  - covr
r_github_packages:
  - jimhester/lintr
cache: packages
sudo: false
warnings_are_errors: true
env:
  - LINTR_COMMENT_BOT=false
addons:
    apt:
        packages:
        - ghostscript
after_success:
  - R CMD INSTALL $PKG_TARBALL
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'library(covr); codecov()'
